
/**
 * Copyright 2013 Marc Schachtel, Germany
 */

package com.cloutree.server.ui.admin;

import java.util.List;

import com.cloutree.server.permission.UIPermissionManager;
import com.cloutree.server.permission.UserManager;
import com.cloutree.server.persistence.entity.Apihost;
import com.cloutree.server.persistence.service.ApihostService;
import com.cloutree.server.session.ClouTreeSession;
import com.cloutree.server.ui.navigation.Views;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

/**
 * TODO
 *
 * @author marc
 *
 * Since 10.09.2013
 */
public class ApiAdministration extends CustomComponent implements View, Button.ClickListener {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private VerticalLayout userAdminMainLayout;

	@AutoGenerated
	private HorizontalLayout buttonLayout;

	@AutoGenerated
	private Button buttonCreateApihost;

	@AutoGenerated
	private Table apihostTable;

	@AutoGenerated
	private Label lblHeader;

	private static final long serialVersionUID = 1L;
    
    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public ApiAdministration() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	
		// IMPLEMENTATION
		this.initApihostTable();
		this.buttonCreateApihost.addClickListener(this);
	
    }

    @SuppressWarnings({ "unchecked", "deprecation" })
    private void initApihostTable() {
	
		this.apihostTable.setImmediate(true);
		this.apihostTable.setEnabled(true);
		this.apihostTable.setSelectable(true);
		
		this.apihostTable.addContainerProperty("Name", String.class,  null);
		this.apihostTable.addContainerProperty("URL", String.class,  null);
		this.apihostTable.addContainerProperty("Description", String.class,  null);
		this.apihostTable.addContainerProperty("Status", Integer.class,  null);
		
		List<Apihost> hosts = null;
		ApihostService service = new ApihostService(ClouTreeSession.getInstance());
		
		hosts = service.getAllAvailableApihosts();
		
		if(hosts == null) return;
		
		for(Apihost host : hosts) {
		    
		    Item item = this.apihostTable.addItem(host.getName());
		    item.getItemProperty("Name").setValue(host.getName());
		    item.getItemProperty("URL").setValue(host.getUrl());
		    item.getItemProperty("Description").setValue(host.getDescription());
		    item.getItemProperty("Status").setValue(host.getStatus());
		}
		
		this.apihostTable.setPageLength(0);
		
		this.apihostTable.addListener(new ItemClickEvent.ItemClickListener() {
			private static final long serialVersionUID = 2068314108919135281L;
			public void itemClick(ItemClickEvent event) {
			    if (event.isDoubleClick()) {
				
				VerticalLayout layout = new VerticalLayout();
				layout.setMargin(false);
				layout.setSpacing(false);
				layout.setSizeFull();
				
				Window dialog = new Window();
				dialog.center();
				dialog.setModal(true);
				dialog.setHeight("500px");
				dialog.setWidth("600px");
				dialog.setResizable(false);
				
				ApihostEditor editor = new ApihostEditor();
				editor.setSizeFull();
				editor.setApihost((String)event.getItemId());
				editor.init();
				layout.addComponent(editor);
				dialog.setCaption("Edit API Host: " + event.getItemId());
				
				dialog.setContent(layout);
				event.getComponent().getUI().addWindow(dialog);
				
			    }
			}
		});
	
    }
    
    @Override
    public void enter(ViewChangeEvent event) {
		if(!UIPermissionManager.getInstance().hasPermission(UserManager.getCurrentUser(), this.getClass())){
		    Notification.show("No Permission to enter this view", Notification.Type.ERROR_MESSAGE);
		    event.getNavigator().navigateTo(Views.ERROR.name());
		}
    }

    /* (non-Javadoc)
     * @see com.vaadin.ui.Button.ClickListener#buttonClick(com.vaadin.ui.Button.ClickEvent)
     */
    @Override
    public void buttonClick(ClickEvent event) {
		VerticalLayout layout = new VerticalLayout();
		layout.setMargin(false);
		layout.setSpacing(false);
		layout.setSizeFull();
		
		Window dialog = new Window();
		dialog.center();
		dialog.setModal(true);
		dialog.setHeight("500px");
		dialog.setWidth("600px");
		dialog.setResizable(false);
		
		ApihostEditor editor = new ApihostEditor();
		editor.setSizeFull();
		editor.init();
		layout.addComponent(editor);
		dialog.setCaption("Add new API Host");
		
		dialog.setContent(layout);
		event.getComponent().getUI().addWindow(dialog);
    }

    @AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// userAdminMainLayout
		userAdminMainLayout = buildUserAdminMainLayout();
		mainLayout.addComponent(userAdminMainLayout,
				"top:0.0px;right:0.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildUserAdminMainLayout() {
		// common part: create layout
		userAdminMainLayout = new VerticalLayout();
		userAdminMainLayout.setImmediate(false);
		userAdminMainLayout.setWidth("100.0%");
		userAdminMainLayout.setHeight("100.0%");
		userAdminMainLayout.setMargin(false);
		userAdminMainLayout.setSpacing(true);
		
		// lblHeader
		lblHeader = new Label();
		lblHeader.setImmediate(false);
		lblHeader.setWidth("-1px");
		lblHeader.setHeight("-1px");
		lblHeader.setValue("API Administration");
		userAdminMainLayout.addComponent(lblHeader);
		
		// apihostTable
		apihostTable = new Table();
		apihostTable.setImmediate(false);
		apihostTable.setWidth("100.0%");
		apihostTable.setHeight("100.0%");
		userAdminMainLayout.addComponent(apihostTable);
		userAdminMainLayout.setExpandRatio(apihostTable, 1.0f);
		
		// buttonLayout
		buttonLayout = buildButtonLayout();
		userAdminMainLayout.addComponent(buttonLayout);
		userAdminMainLayout.setComponentAlignment(buttonLayout, new Alignment(
				34));
		
		return userAdminMainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildButtonLayout() {
		// common part: create layout
		buttonLayout = new HorizontalLayout();
		buttonLayout.setImmediate(false);
		buttonLayout.setWidth("-1px");
		buttonLayout.setHeight("-1px");
		buttonLayout.setMargin(false);
		
		// buttonCreateApihost
		buttonCreateApihost = new Button();
		buttonCreateApihost.setCaption("Add API Host");
		buttonCreateApihost.setImmediate(true);
		buttonCreateApihost.setWidth("-1px");
		buttonCreateApihost.setHeight("-1px");
		buttonLayout.addComponent(buttonCreateApihost);
		
		return buttonLayout;
	}

}
